In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../Data/bank_note_data.txt',delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [3]:
labels = data[:,-1]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [4]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [5]:
X = features
y = labels

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [7]:
len(X_train)

919

In [8]:
len(X)

1372

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler_Object = MinMaxScaler()
scaler_Object.fit(X_train)

scaled_X_train = scaler_Object.transform(X_train)
scaled_X_test = scaler_Object.transform(X_test)


In [10]:
scaled_X_train.max()

1.0000000000000002

In [11]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [12]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [13]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [14]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
5s - loss: 0.6735 - acc: 0.6061
Epoch 2/50
0s - loss: 0.6636 - acc: 0.6507
Epoch 3/50
0s - loss: 0.6543 - acc: 0.6551
Epoch 4/50
0s - loss: 0.6440 - acc: 0.6736
Epoch 5/50
0s - loss: 0.6343 - acc: 0.6801
Epoch 6/50
0s - loss: 0.6240 - acc: 0.6801
Epoch 7/50
0s - loss: 0.6126 - acc: 0.6768
Epoch 8/50
0s - loss: 0.6006 - acc: 0.6779
Epoch 9/50
0s - loss: 0.5877 - acc: 0.6888
Epoch 10/50
0s - loss: 0.5698 - acc: 0.7269
Epoch 11/50
0s - loss: 0.5401 - acc: 0.7497
Epoch 12/50
0s - loss: 0.5158 - acc: 0.7965
Epoch 13/50
0s - loss: 0.4930 - acc: 0.8150
Epoch 14/50
0s - loss: 0.4710 - acc: 0.8183
Epoch 15/50
0s - loss: 0.4511 - acc: 0.8400
Epoch 16/50
0s - loss: 0.4306 - acc: 0.8466
Epoch 17/50
0s - loss: 0.4121 - acc: 0.8694
Epoch 18/50
0s - loss: 0.3933 - acc: 0.8792
Epoch 19/50
0s - loss: 0.3785 - acc: 0.8934
Epoch 20/50
0s - loss: 0.3611 - acc: 0.8901
Epoch 21/50
0s - loss: 0.3463 - acc: 0.9010
Epoch 22/50
0s - loss: 0.3321 - acc: 0.9010
Epoch 23/50
0s - loss: 0.3188 - acc: 0.90

In [16]:
model.metrics_names

['loss', 'acc']

In [17]:
from sklearn.metrics import confusion_matrix,classification_report
predictions = model.predict_classes(scaled_X_test)
confusion_matrix(y_test,predictions)

 32/453 [=>............................] - ETA: 1s

array([[252,   5],
       [ 12, 184]])

In [18]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.95      0.98      0.97       257
        1.0       0.97      0.94      0.96       196

avg / total       0.96      0.96      0.96       453



In [19]:
model.save('Counterfeit_model.h5')

In [21]:
from keras.models import load_model
newModel = load_model('Counterfeit_model.h5')
prediction_Train_data = newModel.predict_classes(scaled_X_train)
confusion_matrix(y_train,prediction_Train_data)

576/919 [=================>............] - ETA: 0s

array([[491,  14],
       [ 21, 393]])

In [22]:
print(classification_report(y_train,prediction_Train_data))

             precision    recall  f1-score   support

        0.0       0.96      0.97      0.97       505
        1.0       0.97      0.95      0.96       414

avg / total       0.96      0.96      0.96       919

